### ISSUE TITLE
auto-completion of issues

### ISSUE THREAD

**Issue by petobens** [shumphrey/fugitive-gitlab.vim#14]
Do you plan to add completion of users, collaborators etc as in https://github.com/tpope/vim-rhubarb? Thank you!

**Comment by shumphrey** [comment]
I was thinking about that today. The answer is probably though not sure when

**Comment by petobens** [comment]
Oka. Thanks!

**Comment by shumphrey** [comment]
Branch [omnifunc](https://github.com/shumphrey/fugitive-gitlab.vim/tree/omnifunc) implements git message completion similar to rhubarb.vim, some differences.

**Comment by petobens** [comment]
Awesome! Thank you :)

**Comment by petobens** [comment]
Hi @shumphrey. I'm trying to use this feature again but there is something I cannot figure how to fix by myself:

I generally use rhubarb to for omni completion in gitcommit buffers with the following settings:
```vim
    au Filetype gitcommit setlocal omnifunc=rhubarb#omnifunc
    au BufEnter *.{git/COMMIT_EDITMSG,gitcommit}
                \ setlocal omnifunc=rhubarb#omnifunc
```
I want to somehow have an if statement (a conditional) that checks if the project has a gitlab remote and then instead of using `rhubarb#omnifunc` for it to default to `gitlab#omnifunc`. Any idea how to do this? Thanks in advance!!

**Comment by petobens** [comment]
Also as far as i understand this only allows to autocomplete after a `#` symbol right? Can it somehow be extended to allow completion after `Fix/Close/See`...? Again thanks :)

**Comment by shumphrey** [comment]
Hi,

Starting with your last question, it should follow loosely what rhubarb does.
Rhubarb supports Fix/Close/etc to work out the starting position of the completion search.
The string list for this plugin was originally taken from rhubarb so in theory, it should be the same unless there's a bug somewhere.

It does complete on anything, not just things starting with # 
So `thing<ctrl-x ctrl-o>` will search for issues with `thing` in the title.

There are some differences to rhubarb, mainly because the gitlab API is different to the github API, but otherwise it should be pretty similar.

One difference, depending on gitlab version, the gitlab API for issues seems *much* slower than github.
Not much I can do about that.

**Comment by shumphrey** [comment]
As to your first question.

I'm not 100% sure what the your example does on top of what rhubarb does itself? rhubarb already installs itself with a similar autocmd, and rhubarb only works for origin remotes, unless I've missed something.
Similarly, at the moment, fugitive-gitlab only works for origin remotes.
Its a real shame that rhubarb and this only support origin for remote name, and I'd love to solve it.

Aside from that, how about this:

```viml
au Filetype gitcommit
    \ if fugitive#buffer().repo().config('remote.origin.url') =~# 'gitlab.com' |
    \   setlocal omnifunc=gitlab#omnifunc |
    \ else |
    \   setlocal omnifunc=rhubarb#omnifunc |
    \ endif
```
The above says, if origin remote url contains the string "gitlab.com", use this plugin's omni complete, otherwise use github.

**Comment by petobens** [comment]
Thanks for the last snippet!

Regarding what I said about Fixes/Closes, i understand that I can write some substring and then the omnifunc will filter accordingly. What I would like is to be able to trigger the omnifunc with the words Fix/Close/See. Currently as it can be seen in the GIF below I can trigger the omni func by always prepending `#` however if i write `Closes <C-X><C-O>` then nothing happens (unless the word `Closes` is part of an existing issues and therefore that issues is selected). Is this possible?

![may-11-2018 12-17-15](https://user-images.githubusercontent.com/2583971/39931975-4796e0ec-5515-11e8-86ae-9675135966f9.gif)

**Comment by shumphrey** [comment]
I'm not sure this is entirely what you were asking for, however, the empty string can now be completed in line with how rhubarb works for github.

`Closes <C-x><C-o>` will now list all open issues by URL as rhubarb does, prefixing # is still required to get numeric list.

**Comment by petobens** [comment]
Yep, exactly what i needed. Thank you!
