### ISSUE TITLE
About `g:fugitive_gitlab_ssh_user`

### ISSUE THREAD

**Issue by letientai299** [shumphrey/fugitive-gitlab.vim#30]
I found `g:fugitive_gitlab_ssh_user` from the code when looking for a way to support our private gitlab . That setting is currently undocumented. I guess you don't want to do so because the current implementation is not satisfied: It can't support multiple gitlab ssh users for different domains.

Perhaps we can deprecate all 3 variables: 

- `fugitive_gitlab_domains`
- `gitlab_api_keys`
- `fugitive_gitlab_ssh_user`

And introduce a new array of objects: `fugitive_gitlab_configs`:

```viml
let g:fugitive_gitlab_configs = [{
  'api_key': '...', 
  'domain': '...',
  'ssh_user': '...'
}]
```

Using that construction, we can have more customization per domains in future if needed. How do you think?

**Comment by shumphrey** [comment]
I'm potentially open to this.
Does vim-rhubarb do anything similar?

**Comment by letientai299** [comment]
After skimmed through vim-rubarb, they only support Github and Github Enterprise, no customization about ssh user. I don't we need to keep the feature set same wit them, do we?

**Comment by alerque** [comment]
The difference here is that Github is a walled garden, a private silo that dictates you connect to them one way (at least as far as SSH usernames go!). Hence there is no need for a configuration option in rhubarb. The username and host component in always `git@github.com:`.

Gitlab support is fundamentally different because it is an open source platform that you can self host. They happen to have a very popular company hosted instance at gitlab.com, so support for 'gitlab.com' is pretty staight-forward. That _could_ be hard coded in. But support for Gitlab itself is a bit more complex because self hosted instances are everywhere. Many of them (especially Omnibus instalations) use the default username, but it is dependent on the host server. It can, and especially when there are other services on a box using the username `git`, be run under any username to issolate the service.

Hence to support Gitlab the ability to customize the hostname _and_ the ssh user is required.

Lastly the issue of support for multiple instance needs to be brought up. I have an account on gitlab.com, host my own instance, and participate in projects hosted on other instances. Unlike Github support, one set of credentials is not enough.

**Comment by shumphrey** [comment]
I'm trying to remember why that variable even exists.
Its used in the regex that pulls out the domain in ssh style git remotes... but we don't otherwise actually use it.
I'm thinking we could just match anything before the @ within reason, and do away with the variable.

**Comment by alerque** [comment]
@shumphrey Don't be too indiscriminate, at least be careful about possible passwords in http formats like `https://user:pass@example.com` I don't know whether `git` itself will save and/or return those values, but if this is a user alterable field it is conceivable such a value could be included beyond just the username.

**Comment by shumphrey** [comment]
> @shumphrey Don't be too indiscriminate, at least be careful about possible passwords in http formats like `https://user:pass@example.com` I don't know whether `git` itself will save and/or return those values, but if this is a user alterable field it is conceivable such a value could be included beyond just the username.

Indeed, the regex that matches domains, needs to take into account (https|ssh)://user:pass@ etc

However, I don't care what the *value* of the user or password is, only that the regex correctly matches the domain. So I have a fair bit of leeway

**Comment by shumphrey** [comment]
Closing this for now. #31 doesn't address the issue of a more flexible config, but does hopefully address the issue of specifying the SSH user (or not actually needing to).
Feel free to open another issue on flexible config if there is another use case.
