### ISSUE TITLE
Write an FAQ

### ISSUE THREAD

**Issue by shumphrey** [shumphrey/fugitive-gitlab.vim#34]
Self hosted gitlab often has quirks such as ssh url being different to web url.
This is solvable with git/ssh settings but needs documenting.

An FAQ would help document this.

**Comment by asdf8601** [comment]
I have the same issue, how did you solve it?

**Comment by shumphrey** [comment]
> I have the same issue, how did you solve it?

Usually with ssh aliases
~/.ssh/config
```
Host my.web.url
  Hostname my.ssh.url
```

**Comment by asdf8601** [comment]
Probably it wasn't the same issue: I could fix it by adding `let g:fugitive_gitlab_domains = ['https://my.web-url']` in my `vim.rc`; after that, all works well. :man_shrugging: 

I save this tip for the future :wink: , Thank you for your support and this plugin it's very useful!

**Comment by cbrownstein** [comment]
Hi,

> Self hosted gitlab often has quirks such as ssh url being different to web url.
> This is solvable with git/ssh settings […]

> I have the same issue, how did you solve it?

> Usually with ssh aliases
> ~/.ssh/config
> 
> ```
> Host my.web.url
>   Hostname my.ssh.url
> ```

This doesn't seem to work anymore since https://github.com/tpope/vim-fugitive/commit/ddea2ecb0ff221f1f4cdba4d3b5ff121c3ff0338 made it so that the true hostname is swapped in for the alias name. The commit message says:

```
If for some reason you need the original URL without modification, pass
a true value as the third parameter:

	let url = FugitiveRemoteUrl('', bufnr(''), 1)
```

I'm not quite sure how to use that. Help would be greatly appreciated. Once I figure that out, I'll happily write a FAQ.

**Comment by shumphrey** [comment]
The `FugitiveRemoteUrl` command is to get the unaliased URL in code, it probably won't help specifically with `:GBrowse`

So some GitLab users expect the SSH and web urls to be different, and they're doing this with ~/.ssh/config and putting the web url as the origin, but ssh config aliases it back to ssh url.

I think if people are relying on fugitive to *not* expand that alias for `:GBrowse` then that needs discussing with @tpope in the fugitive repo.

There are probably clever alternatives with fake remotes or something.
e.g. create a "web" remote for the web url and do `:GBrowse @web`, which could then be mapped to something more convenient in local vimrc.

**Comment by tpope** [comment]
> ```
> Host my.web.url
>   Hostname my.ssh.url
> ```

Does this serve a higher purpose, or is it _only_ to trick Fugitive into thinking the remote URL is something different that it actually is?

**Comment by shumphrey** [comment]
> > ```
> > Host my.web.url
> >   Hostname my.ssh.url
> > ```
> 
> Does this serve a higher purpose, or is it _only_ to trick Fugitive into thinking the remote URL is something different that it actually is?

The only use case I'm aware of is specifically to trick fugitive.
I'm sure there must be better ways.
Specifically the case when a ~private~ self-hosted GitLab has made the SSH url be different to the web url.

**Comment by tpope** [comment]
I think the solution here is to give the configuration mechanism the ability to specify the URL. Something like:

```vim
let g:gitlab_domains = {
      \ 'my.ssh.url': 'https://my.web.url',
      \ }
```

This also makes it easy for the user to force `http://` or `https://`, another common conundrum for self hosted solutions. If I was writing Rhubarb today, this is how I would do it.

**Comment by tpope** [comment]
This tickled me so I prototyped a version in Rhubarb at https://github.com/tpope/vim-rhubarb/tree/enterprise-dictionary. It works like this:

```
let g:github_enterprise_urls = {
      \ 'simple.host': v:true,
      \ 'ssh.host': 'https://www.host',
      \ 'insecure.host': 'http://insecure.host',
      \ }
```

I would expect it to be more or less a drop in replacement for fugitive-gitlab.vim's implementation, although it looks like you might handle the presence of a port number a bit differently.

*Edit: new commit with better port handling*

**Comment by shumphrey** [comment]
Basically the same code at https://github.com/shumphrey/fugitive-gitlab.vim/tree/expanded_config

**Comment by tpope** [comment]
One thing I omitted is that my implementation also supports this:

```vim
let g:github_enterprise_urls = {
      \ 'ssh://ssh.host': 'https://www.host',
      \}
```

This tightens thing down a bit so that `http://ssh.host` *doesn't* get changed, which almost never matters, but also conveys intent a bit better, which sometimes does matter. This behavior appears to have made it over into the `expanded_config` branch as well, good deal.

I'm currently spiking on adding a version of this to Fugitive itself but it's not looking good. The fact that most hosting providers treat `user@host:path` and `user@host:/path` as the same—but that's not a universal guarantee that Fugitive can take for granted—really throws a spanner in the works. I'll report back once I succeed or give up.

**Comment by tpope** [comment]
I've decided Fugitive level configuration won't make the cut for the upcoming release. Whether it will eventually land in a month, a year, or never, I don't know. I've merged the dictionary config on Rhubarb but left it out of the documentation for now. I would softly encourage you to do the same, although you might also want to document it as it seems to be a more common use case here.

P.S. When you have some time, could you check `curl -I -X GET https://self.hosted.gitlab/user/repo.git/info/refs?service=git-upload-pack` and tell me if you can autodetect a Gitlab installation based on that? Looking at `gitlab.com`, the `gitlab-lb` and `gitlab-sv` headers look promising. I ask because if we can autodetect HTTP, then an SSH to HTTP Fugitive option could potentially cover 100% of configuration, no more per-plugin config variables.

**Comment by shumphrey** [comment]
I've merged the branch without docs for now also.

Regarding curl.
Running GitLab out of a docker container, I can't find any way of detecting GitLab from the response.
The gitlab-lb and gitlab-sv headers do not exist.

**Comment by tpope** [comment]
Dang, well, good to rule it out early I guess. Do hit me up if you think of an elegant solution, where elegant includes "not parsing HTML" and "not querying a specific URL that only GitLab has".

**Comment by shumphrey** [comment]
SSH/Web differences are now documented in README via #37 so closing this slightly offtopic issue for now.
